#!/usr/bin/bash

declare -r workdir="$1";
declare -r srcFile="$2";
declare -r wordFile="wordPairs.txt";

declare fileList=$(ls "${workdir}");
declare wordAList=();
declare wordBList=();
declare preCrit0List=();
declare preCrit1List=();
declare crit0List=();
declare crit1List=();

for f in ${fileList}; do
	declare wordA=$(echo $f | cut -f2 -d_ | cut -f1 -d. | cut -f1 -d-);
	declare wordB=$(echo $f | cut -f2 -d_ | cut -f1 -d. | cut -f2 -d-);
	wordAList+=(${wordA});
	wordBList+=(${wordB});

	declare preCrit0=$(cat ${workdir}/$f | head -n5 | tail -n 1);
	declare preCrit1=$(cat ${workdir}/$f | head -n6 | tail -n 1);
	preCrit0List+=(${preCrit0});
	preCrit1List+=(${preCrit1});
done

for ((i=0; i < ${#wordAList[@]}; ++i)); do
	echo ${wordAList[$i]} >> ${wordFile};
	echo ${wordBList[$i]} >> ${wordFile};
done

declare output=( $(./build/src/calcDist ${srcFile} ${wordFile}) );
for ((i=0; i < ${#output[@]}; ++i)); do
	if (( i % 2 == 0 )); then
		crit0List+=(${output[$i]});
	else
		crit1List+=(${output[$i]});
	fi
done

for ((i=0; i < ${#wordAList[@]}; ++i)); do
	echo ${wordAList[$i]} ${wordBList[$i]};
	echo ${crit0List[$i]};
	echo ${preCrit0List[$i]};
	echo ${crit1List[$i]};
	echo ${preCrit1List[$i]};
done
