#!/usr/bin/bash

# This script compares histogram files using the cmp utility

declare -r referenceFilesDir="$1";
declare -r targetFilesDir="$2";

if [ -z "${referenceFilesDir}" ]; then
	echo "The reference files directory must be specified";
	exit 1;
fi

if [ -z "${targetFilesDir}" ]; then
	echo "The target files dir must be specified";
	exit 1;
fi

declare entryCnt="$(echo "$(ls "${referenceFilesDir}")" | wc -l)";
entryCnt="${entryCnt// /}";
declare entry="0";
declare mCnt="0";

for refFile in $(ls "${referenceFilesDir}"); do
	declare wordA=$(echo ${refFile} | cut -f2 -d_ | cut -f1 -d. | cut -f1 -d-);
	declare wordB=$(echo ${refFile} | cut -f2 -d_ | cut -f1 -d. | cut -f2 -d-);

	declare mismatch="false";

	if cmp -s "${referenceFilesDir}/${refFile}" "${targetFilesDir}/${wordA}_${wordB}.txt"; then
		 echo "${wordA} ${wordB}"
		 mismatch="true"
		 mCnt=$((mCnt + 1))
	fi

	entry=$((entry + 1));

	if [ "${mismatch}" != "true" ]; then
		printf "\r${entry}/${entryCnt} OK";
	fi
done

echo "";

if [ "${mismatch}" = "true" ]; then
	echo "${mCnt} mismatches";
fi
