#!/usr/bin/bash

declare -r referenceFilesDir="$1";
declare -r wordStatFile="$2";

if [ -z "${referenceFilesDir}" ]; then
	echo "The reference files directory must be specified";
	exit 1;
fi

if [ -z "${wordStatFile}" ]; then
	echo "The word stat file must be specified";
	exit 1;
fi

tolerance=1e-9  # define a small tolerance for floating-point comparisons

declare mCnt="0";

for refFile in $(ls "${referenceFilesDir}"); do
	declare wordA=$(echo ${refFile} | cut -f2 -d_ | cut -f1 -d. | cut -f1 -d-);
	declare wordB=$(echo ${refFile} | cut -f2 -d_ | cut -f1 -d. | cut -f2 -d-);

	declare regex="^${wordA} ${wordB}\$";

	declare pairInfo="$(cat ${wordStatFile} | grep -E "${regex}" -A5)";
	declare distCount="$(echo "${pairInfo}" | grep -E "count" | tr -s ' ' | cut -f2 -d' ')";
	declare minDist="$(echo "${pairInfo}" | grep -E "minDistance" | tr -s ' ' | cut -f2 -d' ')";
	declare maxDist="$(echo "${pairInfo}" | grep -E "maxDistance" | tr -s ' ' | cut -f2 -d' ')";
	declare avgDist="$(echo "${pairInfo}" | grep -E "avgDistance" | tr -s ' ' | cut -f2 -d' ')";
	declare sqVariant="$(echo "${pairInfo}" | grep -E "sqVariant" | tr -s ' ' | cut -f2 -d' ')";

	declare refDistCount="$(cat ${referenceFilesDir}/${refFile} | head -n1)";
	declare refMinDist="$(cat ${referenceFilesDir}/${refFile} | head -n2 | tail -n1)";
	declare refMaxDist="$(cat ${referenceFilesDir}/${refFile} | head -n3 | tail -n1)";
	declare refAvgDist="$(cat ${referenceFilesDir}/${refFile} | head -n5 | tail -n1)";
	declare refSqVariant="$(cat ${referenceFilesDir}/${refFile} | head -n6 | tail -n1)";

	declare mismatch="false";

	if !(( $(echo "scale=10; sqrt((${distCount} - ${refDistCount})^2) < $tolerance" | bc -l) )) || \
		 !(( $(echo "scale=10; sqrt((${maxDist} - ${refMaxDist})^2) < $tolerance" | bc -l) )) || \
		 !(( $(echo "scale=10; sqrt((${minDist} - ${refMinDist})^2) < $tolerance" | bc -l) )) || \
		 !(( $(echo "scale=10; sqrt((${avgDist} - ${refAvgDist})^2) < $tolerance" | bc -l) )) || \
		 !(( $(echo "scale=10; sqrt((${sqVariant} - ${refSqVariant})^2) < $tolerance" | bc -l) )); then
		mismatch="true";
		mCnt=$((mCnt + 1));
	fi

	if [ "${mismatch}" = "true" ]; then
		echo "${wordA} ${wordB}";
		echo "tgt dst: ${distCount}";
		echo "ref dst: ${refDistCount}"
		echo "tgt min: ${minDist}";
		echo "ref min: ${refMinDist}";
		echo "tgt max: ${maxDist}";
		echo "ref max: ${refMaxDist}";
		echo "tgt avg: ${avgDist}";
		echo "ref avg: ${refAvgDist}";
		echo "tgt sqv: ${sqVariant}";
		echo "ref sqv: ${refSqVariant}";
	fi
done

if [ "${mismatch}" = "true" ]; then
	echo "${mCnt} mismatches";
fi
